name: fluffychat
base: core18
adopt-info: fluffychat
summary: The cutest messenger in the Matrix network
description: |
  FluffyChat is an open source, nonprofit and cute matrix messenger app. The app is easy to use but secure and decentralized.


  ## Features

  - Send all kinds of messages, images and files
  - Voice messages
  - Location sharing
  - Push notifications
  - Unlimited private and public group chats
  - Public channels with thousands of participants
  - Feature rich group moderation including all matrix features
  - Discover and join public groups
  - Dark mode
  - Hides complexity of Matrix IDs behind simple QR codes
  - Custom emotes and stickers
  - Video calls via sharing links to Jitsi
  - Spaces
  - Compatible with Element, Nheko, NeoChat and all other Matrix apps
  - End to end encryption
  - Emoji verification & cross signing
  - And much more...


  ## FluffyChat comes with a dream

  Imagine a world where everyone can choose the messenger they like and is still able to chat with all of their friends.

  A world where there are no companies spying on you when you send selfies to friends and lovers.

  And a world where apps are made for fluffyness and not for profit. ♥

  Join the community: https://matrix.to/#/#fluffychat:matrix.org
  Website: http://fluffychat.im
  Microblog: https://metalhead.club/@krille

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  olm:
    plugin: cmake
    source: https://gitlab.matrix.org/matrix-org/olm.git
    source-type: git
    source-tag: 3.2.9
    build-packages:
      - g++
  fluffychat:
    plugin: flutter
    source: https://gitlab.com/famedly/fluffychat.git
    flutter-target: lib/main.dart
    # Must be after: flutter-extension to set the flutter channel; flutter-extension will set it to “dev”, which is unhelpful
    after:
      - flutter-extension
    override-build: |
      snapcraftctl set-version $(git describe --always --tag)
      snapcraftctl build
    override-pull: |
      snapcraftctl pull
      flutter channel stable
      flutter upgrade
    build-packages:
      - libjsoncpp-dev
      - libsecret-1-dev
      - libwebkit2gtk-4.0-dev
    stage-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
      - libwebkit2gtk-4.0-dev

slots:
  dbus-svc:
    interface: dbus
    bus: session
    name: chat.fluffy.fluffychat

apps:
  fluffychat:
    extensions:
      - flutter-dev
    command: fluffychat
    plugs:
      - network
      - mount-observe
      - x11
      - home
      - removable-media
      - browser-support
      - password-manager-service
    slots:
      - dbus-svc
