name: fluffychat
base: core22
adopt-info: fluffychat
summary: The cutest messenger in the Matrix network
description: |
  FluffyChat is an open source, nonprofit and cute matrix messenger app. The app is easy to use but secure and decentralized.


  ## Features

  - Send all kinds of messages, images and files
  - Voice messages
  - Location sharing
  - Push notifications
  - Unlimited private and public group chats
  - Public channels with thousands of participants
  - Feature rich group moderation including all matrix features
  - Discover and join public groups
  - Dark mode
  - Hides complexity of Matrix IDs behind simple QR codes
  - Custom emotes and stickers
  - Video calls via sharing links to Jitsi
  - Spaces
  - Compatible with Element, Nheko, NeoChat and all other Matrix apps
  - End to end encryption
  - Emoji verification & cross signing
  - And much more...


  ## FluffyChat comes with a dream

  Imagine a world where everyone can choose the messenger they like and is still able to chat with all of their friends.

  A world where there are no companies spying on you when you send selfies to friends and lovers.

  And a world where apps are made for fluffyness and not for profit. ♥

  Join the community: https://matrix.to/#/#fluffychat:matrix.org
  Website: http://fluffychat.im
  Microblog: https://metalhead.club/@krille

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
# Ubuntu 22.04 already has libolm 3.2.10, so we don't need to build it ourselves
# The original build part is left here, in case we need to bump libolm version later.
#  olm:
#    plugin: cmake
#    configflags:
#      - -DCMAKE_INSTALL_PREFIX=/usr
#    source: https://gitlab.matrix.org/matrix-org/olm.git
#    source-type: git
#    source-tag: 3.2.9
#    build-packages:
#      - g++
  fluffychat:
    plugin: flutter
    source: https://gitlab.com/famedly/fluffychat.git
    flutter-target: lib/main.dart
    override-build: |
      craftctl set version=$(git describe --always --tag)
      craftctl default
    build-packages:
      - libjsoncpp-dev
      - libolm-dev
   stage-packages:
      - libjsoncpp-dev
      - libglu1-mesa
      - freeglut3
      - libolm-dev
slots:
  dbus-svc:
    interface: dbus
    bus: session
    name: chat.fluffy.fluffychat

apps:
  fluffychat:
    extensions:
      - gnome
    command: bin/fluffychat
    plugs:
      - audio-playback
      - browser-support
      - home
      - mount-observe
      - network
      - password-manager-service
      - removable-media
    slots:
      - dbus-svc
