name: fluffychat
base: core18
version: git
summary: The cutest messenger in the Matrix network
description: |
  FluffyChat is an open source, nonprofit and cute matrix messenger app. The app is easy to use but secure and decentralized.


  ## Features

  - Send all kinds of messages, images and files
  - Voice messages
  - Location sharing
  - Push notifications
  - Unlimited private and public group chats
  - Public channels with thousands of participants
  - Feature rich group moderation including all matrix features
  - Discover and join public groups
  - Dark mode
  - Hides complexity of Matrix IDs behind simple QR codes
  - Custom emotes and stickers
  - Video calls via sharing links to Jitsi
  - Spaces
  - Compatible with Element, Nheko, NeoChat and all other Matrix apps
  - End to end encryption
  - Emoji verification & cross signing
  - And much more...


  ## FluffyChat comes with a dream

  Imagine a world where everyone can choose the messenger they like and is still able to chat with all of their friends.

  A world where there are no companies spying on you when you send selfies to friends and lovers.

  And a world where apps are made for fluffyness and not for profit. ♥

  Join the community: https://matrix.to/#/#fluffychat:matrix.org
  Website: http://fluffychat.im
  Microblog: https://metalhead.club/@krille

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
    build-error: ignore
  - build-on: ppc64el
    build-error: ignore

parts:
  olm:
    plugin: cmake
    source: https://gitlab.matrix.org/matrix-org/olm.git
    source-type: git
    source-tag: 3.2.9
    build-packages:
      - g++
  fluffychat:
    plugin: flutter
    source: https://gitlab.com/famedly/fluffychat.git
    flutter-target: lib/main.dart
    # Must be after: flutter-extension to set the flutter channel; flutter-extension will set it to “dev”, which is unhelpful
    after:
      - flutter-extension
    override-pull: |
      snapcraftctl pull
      flutter channel stable
      flutter upgrade
    build-packages:
      - libjsoncpp-dev
      - libsecret-1-dev
    stage-packages:
      - libsqlite3-dev
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libsecret-1-dev
      - libjsoncpp-dev
      - libatspi2.0-0
      - libcairo-gobject2
      - libcairo2
      - libdatrie1
      - libegl1
      - libepoxy0
      - libfontconfig1
      - libfreetype6
      - libgdk-pixbuf2.0-0
      - libglvnd0
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1
slots:
  dbus-svc:
    interface: dbus
    bus: session
    name: chat.fluffy.fluffychat

apps:
  fluffychat:
    extensions:
      - flutter-dev
    command: fluffychat
    plugs:
      - network
      - home
    slots:
      - dbus-svc

